# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  default_filter_set_settings:
    format: webp
  webp:
    generate: true
  filter_sets:
    cache: ~
    thumb:
      quality: 75
      filters:
        thumbnail: { size: [ 224, 200 ], mode: outbound }
    avatar:
      quality: 75
      filters:
        small: { size: [ 80, 80 ], mode: outbound }
    160x160:
      quality: 75
      filters:
        thumbnail: { size: [ 160, 160 ], mode: outbound }
    238x200:
      quality: 75
      filters:
        thumbnail: { size: [ 238, 200 ], mode: outbound }
    232x200:
      quality: 75
      filters:
        thumbnail: { size: [ 238, 200 ], mode: outbound }
    50x50:
      quality: 75
      filters:
        thumbnail: { size: [ 50, 50 ], mode: outbound }
    certificate:
      quality: 75
      filters:
        thumbnail: { size: [ 238, 200 ], mode: inset }

